Server/create about.json call thing
TEAM-AAAAAAAAAAAAAAAA/AREA pull request #108
Opened 2023-02-27 14:53 UTC by EmileEttel

Allows you to call the server ip on /about.json and get a proper response

2023-02-27 14:58 UTC, Cavonstavant approved these changes

2023-02-27 15:15 UTC, aurelenc requested changes
swap actions and reactions

2023-02-28 07:41 UTC, aurelenc requested changes

2023-02-28 07:41 UTC, aurelenc commented on server/src/app.ts
> +    res.status(200).send(about);
```suggestion
    res.status(200).json(about);
```

2023-02-28 08:13 UTC, merged