Docker/bot discord
TEAM-AAAAAAAAAAAAAAAA/AREA pull request #136
Opened 2023-03-03 15:05 UTC by Bootoyka

2023-03-03 15:25 UTC, Cavonstavant approved these changes

2023-03-03 16:07 UTC, aurelenc approved these changes

2023-03-03 17:37 UTC, aurelenc requested changes
Discord bot can't fetch the server if both are executed inside a container

2023-03-04 07:59 UTC, Cavonstavant requested changes
i only review PRs that goes to main

2023-03-04 10:42 UTC, merged