8 dockerconfigure services ports volumes and deps
TEAM-AAAAAAAAAAAAAAAA/AREA pull request #47
Opened 2023-01-17 23:20 UTC by Bootoyka

This pr delivers a first version of docker-compose.yml & first version of web_server Dockerfile according to the subject recommandation

close #8

2023-01-17 23:44 UTC, Bootoyka commented
This is more draft than real pr, didn't find how to turn it draft

2023-01-18 15:01 UTC, EmileEttel approved these changes
LGTM

2023-01-18 15:59 UTC, Cavonstavant approved these changes

2023-01-19 09:44 UTC, Bootoyka commented
Let me merge this one please to be sure that everything is working good

2023-01-19 11:06 UTC, majent4 approved these changes

2023-01-19 11:22 UTC, Cavonstavant requested changes

2023-01-19 11:22 UTC, Cavonstavant commented on docker-compose.yml
> +      - "8082:8082"
```suggestion
      - "4000:4000"
```

2023-01-19 11:27 UTC, Cavonstavant requested changes

2023-01-19 11:27 UTC, Cavonstavant commented on server/Dockerfile
> +
don't run things as root on the container

```suggestion
USER www-data
```

2023-01-19 11:29 UTC, Cavonstavant commented on server/Dockerfile
> +
I should note that USER must be put on top of the 3rd line: `RUN mkdir -p /usr/src/app` or the folder will be created as root

2023-01-19 21:53 UTC, merged